version: '3'
services:
  nodered:
    container_name: ${PROJECT_NAME}-nodered
    image: nodered/node-red
    restart: always
    volumes:
      - ./data/nodered:/data
    ports:
      - 1880:1880

  mosquitto:
    container_name: ${PROJECT_NAME}-mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/data
    ports:
      - 1883:1883

  influxdb:
    container_name: ${PROJECT_NAME}-influxdb
    image: arm32v7/influxdb:latest
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=${DB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_DB=${DB_NAME}

  grafana:
    container_name: ${PROJECT_NAME}-grafana
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    user: ${UID}
    volumes:
      - ./data/grafana:/var/lib/grafana
